"""add_repeat_type_and_ability

Revision ID: 23ff140c7dab
Revises: 8f7b2a401db1
Create Date: 2026-06-03 20:06:44.002905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ff140c7dab'
down_revision: Union[str, Sequence[str], None] = '8f7b2a401db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('repeat_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'repeat_type')
    # ### end Alembic commands ###
